### ISSUE TITLE
Lengthy scrollview inside safe are element causes element to stretch

### ISSUE THREAD

**Issue by sathyarajshetigar** [artstorm/ui-toolkit-safe-area#7]
I have a large scrollView with lots of items 
Root
->SafeArea
---->ScrollViewParent height: 100%, Grow: 1
------->ScrollView
----------->Items

if the ScrollViewParent  is not part of safe area element it works fine and covers just the screen and I can scroll items as expected.
But if its the child of Safe Area then it scales to cover the entire length of scrollview which makes it impossible to scroll. 
![image](https://github.com/artstorm/ui-toolkit-safe-area/assets/42057975/86e2c2de-f681-4633-8e9a-f22f97c9d916)

**Comment by artstorm** [comment]
If this issue remains, please open a new issue and attach content that reproduces the problem.
